---
# playbook.yml
- name: 'Provision Image'
  hosts: localhost
  become_user: root
  become_method: sudo
  become: true

  tasks:
    - name: install Apache
      package:
        name: 'httpd'
        state: present