# playbook.yml
- name: 'Provision Image'
  hosts: all
  become_user: root
  become_method: sudo
  become: true

  tasks:
    - name: install Apache2
      package:
        name: 'apache2'
        state: latest